### ISSUE TITLE
Update or replace django-sekizai

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#10]
We use the package [django-sekizai](https://github.com/ojii/django-sekizai) in edx/django-wiki and edx/edx-platform. It hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by MaferMazu** [comment]
I opened a [PR](https://github.com/django-cms/django-sekizai/pull/102) to add Django 3.2 in the tests and an [issue](https://github.com/django-cms/django-sekizai/issues/103) in the package [django-sekizai](https://github.com/ojii/django-sekizai)

In [my branch](https://github.com/MaferMazu/django-sekizai/tree/mfmz/add-support-django-32) there were no problems testing this package with Django 3.2

**Comment by natabene** [comment]
@MaferMazu Thank you so much for looking into this, I appreciate! Can you let me know once the PR merges?

**Comment by MaferMazu** [comment]
> @MaferMazu Thank you so much for looking into this, I appreciate! Can you let me know once the PR merges?

Sure. I will do it.

**Comment by MaferMazu** [comment]
I still have not had a response from the maintainers, however the [PR](https://github.com/django-cms/django-sekizai/pull/102) I did tests that [there are no errors in the tests with Django 3.2](https://github.com/MaferMazu/django-sekizai/runs/3355373466)

**Comment by natabene** [comment]
@MaferMazu Thanks for an update! @awais786 How do you suggest we proceed?

**Comment by awais786** [comment]
@MaferMazu I just tagged the most active maintainer on your PR. We have to wait for next few days. I will keep an eye and remind them.

**Comment by MaferMazu** [comment]
Ok. Thanks :D

**Comment by MaferMazu** [comment]
The maintainers have already merged my PR, thanks for your help. The release is still missing, let's wait for what they tell me.

**Comment by natabene** [comment]
@MaferMazu Wonderful, thanks for an update.

**Comment by UsamaSadiq** [comment]
Hi @MaferMazu looks like the version [django-sekizai==2.1.0](https://github.com/django-cms/django-sekizai/releases/tag/2.1.0) with `Django 3.2` support was released soon after you created the issue but it wasn't updated. 
Thanks a lot for your efforts on this issue. I'll close this issue now.
