### ISSUE TITLE
Notify arbi-bom in Python Requirements Upgrade workflows

### ISSUE THREAD

**Issue by UsamaSadiq** [edx/upgrades#111]
## Description
- Find the repos under the `arbi-bom` team ownership that do not have `team_viewers` option enabled in the `Python Requirements Upgrade workflow`. 
- Enable the `team_viewers`, `email_address` and `enable_success_notification` options.

**Comment by iamsobanjaved** [comment]
is this done?

**Comment by UsamaSadiq** [comment]
Issue https://github.com/openedx/axim-engineering/issues/755 has been completed  to update the mentioned repositories so this issue can be closed now.
