### ISSUE TITLE
fix docs build failure for urllib3 v2 version

### ISSUE THREAD

**Issue by UsamaSadiq** [edx/upgrades#112]
## Description
- `urllib3>2.0.0` has now dropped support for `OpenSSL<1.1.1`. See the issue https://github.com/urllib3/urllib3/issues/2168 for details. 
- Updating the `urllib3>2.0.0` now fails the docs build. See an example failure build: https://readthedocs.org/projects/django-config-models/builds/20528412/ with the following leading error log: 
```
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2n  7 Dec 2017. See: https://github.com/urllib3/urllib3/issues/2168
```
- This is a breaking change for the 190+ edx [repos](https://docs.google.com/spreadsheets/d/1VCxNVq-niT-uv5BFmsYPF21r6I2-IQ-GJbidF0zUPBc/edit#gid=921158295) which have `urllib3` as dependency and use it for running docs checks since we are currently running `Python<3.10` and are upgrading `urllib3` to `v2.0` as mentioned in the urllib3 issue which is mentioned above. 

## Suggested Fix
- See https://github.com/openedx/docs.openedx.org/pull/324/files for an example. The docs break when building on the deprecated ReadTheDocs machines but you can update .readthedocs.yml to use newer machines that have the more up-to-date version of OpenSSL.

**Comment by feanil** [comment]
@UsamaSadiq You don't need to pin urllib3, you can fix forward on the docs.  See https://github.com/openedx/docs.openedx.org/pull/324/files for an example.  The docs break when building on the deprecated ReadTheDocs machines but you can update `.readthedocs.yml` to use newer machines that have the more up-to-date version of OpenSSL.

**Comment by UsamaSadiq** [comment]
Thanks @feanil 
I was also going through the discussions to find a way to fix forward since pinning the dependency would be the last way. I'll go ahead and make the suggested fix in the affected repo workflows.

**Comment by UsamaSadiq** [comment]
Fix for this issue would be to specify the OS version to include latest OpenSSL build dependency in `.readthedocs.yml` similar to https://github.com/openedx/django-config-models/pull/279/files#diff-cde814ef2f549dc093f5b8fc533b7e8f47e7b32a8081e0760e57d5c25a1139d9R17
