### ISSUE TITLE
Update or replace newrelic

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#15]
We use the package [newrelic](https://github.com/newrelic/newrelic-python-agent) in edx/blockstore, edx/completion, edx/course-discovery, edx/credentials, edx/demographics, edx/django-config-models, edx/django-splash, edx/ecommerce, edx/ecommerce-worker, edx/edx-analytics-dashboard, edx/edx-analytics-data-api, edx/edx-bulk-grades, edx/edx-django-utils, edx/edx-drf-extensions, edx/edx-e2e-tests, edx/edx-enterprise, edx/edx-enterprise-data, edx/edx-notes-api, edx/edx-ora2, edx/edx-organizations, edx/edx-platform, edx/edx-proctoring, edx/edx-rbac, edx/edx-rest-api-client, edx/edx-toggles, edx/edx-val, edx/edx-when, edx/enterprise-catalog, edx/event-routing-backends, edx/license-manager, edx/portal-designer, edx/registrar, edx/staff_graded-xblock, edx/super-csv, edx/taxonomy-connector, edx/video-encode-manager, edx/xqueue, edx/xqueue-watcher. It hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by jmbowman** [comment]
I think she's still out for another day or two, but I can go ahead and assign it to you.  Thanks for looking into this!

**Comment by jfavellar90** [comment]
Added an issue in https://github.com/newrelic/newrelic-python-agent/issues/343

**Comment by natabene** [comment]
@jfavellar90 Thank you for an update!

**Comment by jfavellar90** [comment]
Added a PR in https://github.com/newrelic/newrelic-python-agent/pull/344

**Comment by jfavellar90** [comment]
The PR was already merged in the repo. Now it has officially Django 3.2 support in master. Hopefully, we'll get a new release of the library with these changes included in the next few days. @natabene  do you agree on marking this task as done?

**Comment by natabene** [comment]
@jfavellar90 Thank you for an update, this is great news! @jmbowman Do you think we can mark it is done or would you rather wait for a release?

**Comment by natabene** [comment]
@jfavellar90 Could you please check back periodically to see if that release has been done and update us here? That would be most appreciated.

**Comment by jfavellar90** [comment]
@natabene sure thing! I'll let you know once a new release including Django 3.2 support is published

**Comment by jfavellar90** [comment]
@natabene the new release was created in the library: https://github.com/newrelic/newrelic-python-agent/releases/tag/v6.10.0.165 and this contains the code adding support for Django 3.2. Unless there's something else to do, I think this task can be marked as DONE

**Comment by natabene** [comment]
Thank you @jfavellar90 I am closing this.
