### ISSUE TITLE
Update or replace django-taggit-serializer

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#18]
We use the package [django-taggit-serializer](https://github.com/glemmaPaul/django-taggit-serializer) in edx/course-discovery. This package was last released in 2018 and it hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by regisb** [comment]
The django-taggit repo has been moved to jazzband: https://github.com/jazzband/django-taggit
Development has restarted and 1.5.1 is now the latest release: https://pypi.org/project/django-taggit/

Feel free to assign this issue to me.

**Comment by natabene** [comment]
@regisb Thanks so much for picking this up! I will assign to you, please update us on your progress here.

**Comment by natabene** [comment]
@jmbowman Removing this from our dependency table.
