### ISSUE TITLE
Update or replace django-autocomplete-light

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#20]
We use the package [django-autocomplete-light](https://github.com/yourlabs/django-autocomplete-light) in edx/course-discovery. Some progress has been made for Django 3.2 but It doesn't officially support Django3.2 yet. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by cmltaWt0** [comment]
Some work in progress. https://github.com/yourlabs/django-autocomplete-light/issues/1258
Probably we need to help the maintainer.

**Comment by natabene** [comment]
@cmltaWt0 Thank you for finding this, would you be able to help the maintainer? Could I assign this to you? Any help would be much appreciated.

**Comment by cmltaWt0** [comment]
@natabene Yeap, please assign. I can work on it.

**Comment by cmltaWt0** [comment]
Django3.2 support was released as release candidate as [https://pypi.org/project/django-autocomplete-light/3.9.0rc1/](3.9.0rc1)

I'm going to test it and create PR in positive case.

**Comment by natabene** [comment]
@cmltaWt0 Thank so much for an update.

**Comment by cmltaWt0** [comment]
Tested locally and opened PR with RC [3.9.0rc1](https://pypi.org/project/django-autocomplete-light/3.9.0rc1/) as a candidate for upgrade.

**Comment by cmltaWt0** [comment]
@natabene PR has been merged. Is it up to you to proceed this issue further? (to the closed state)

**Comment by natabene** [comment]
@cmltaWt0 Thanks so much for an update, closing.
