### ISSUE TITLE
Update or replace django-environ

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#21]
We use the package [django-environ](https://github.com/joke2k/django-environ) in edx/blockstore. This package was last released in 2018 and it hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by BbrSofiane** [comment]
Hey, I'm happy to take this one.

**Comment by natabene** [comment]
@BbrSofiane Thank you for reaching out, I highly appreciate your interest and help with this. I have assigned this task to you. Please feel free to open a PR once you are ready, I will take care of it from there on.

**Comment by BbrSofiane** [comment]
The original [django-environ](https://github.com/joke2k/django-environ) repo doesn't seem to be maintained and despite other prompts (@joke2k/django-environ#292 and @joke2k/django-environ#282) it doesn't look like the maintainer is interested in bringing it back to life.

A fork was created, [django-environ-2](https://pypi.org/project/django-environ-2/), and that one is actively maintained and currently supports Django 3.2.

**Comment by BbrSofiane** [comment]
Opened edx/blockstore#121.

**Comment by natabene** [comment]
@BbrSofiane Looks like https://github.com/edx/blockstore/pull/121 was merged.

**Comment by BbrSofiane** [comment]
@natabene turns out I have to make another change. 

The library I used, django-environ-2, is archived and its maintainer is now looking after django-environ which has now been updated to support Django 3.2. 

I'll create a new PR.

**Comment by natabene** [comment]
@BbrSofiane Thanks so much for your update!

**Comment by natabene** [comment]
@BbrSofiane Thank you for an update, we will review.

**Comment by UsamaSadiq** [comment]
@BbrSofiane thanks for your help on this issue. After reviewing the changes, I'll now close this issue.
