### ISSUE TITLE
Update or replace django-dotenv

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#22]
We use the package [django-dotenv ](https://github.com/jpadilla/django-dotenv)in edx/openedxstats. This package was last released in 2017 and it hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by shimulch** [comment]
Hi, I want to take this one. We can switch to [django-environ-2](https://github.com/edx/upgrades/issues/21)

**Comment by natabene** [comment]
@shimulch Thank you so much for reaching out. I will assign this to you. Please let me know once this is done.

**Comment by shimulch** [comment]
@natabene Opened https://github.com/edx/openedxstats/pull/112

**Comment by natabene** [comment]
[edx/openedxstats#112](https://github.com/edx/openedxstats/pull/112) was Merged. @Jawayria Do we consider it Done now?

**Comment by awais786** [comment]
Yes its Done.

**Comment by UsamaSadiq** [comment]
As per the [discussion](https://github.com/edx/upgrades/issues/21#issuecomment-915869896), it looks like `django-environ2` was dropped in favour of `django-environ` and `django-environ` now has `Django 3.2` support as well. I would like to reopen this issue for now to replace `django-environ2` with `django-environ`. For reference the PR https://github.com/openedx/blockstore/pull/128 can be referenced.

**Comment by UsamaSadiq** [comment]
@shimulch  since you worked on this issue before, would you like to pick this up again to replace `django-environ-2` with `django-environ`?
