### ISSUE TITLE
Update or replace django-elasticsearch-dsl-drf

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#24]
We use the package [django-elasticsearch-dsl-drf](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf) in edx/course-discovery, edx/edx-notes-api. It hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by jramnai** [comment]
@jmbowman, `django-elasticsearch-dsl-drf` already supports Django 3.2 with the master branch and I have created [an issue](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/issues/270) to make a new release of the package.

**Comment by jramnai** [comment]
@jmbowman, [0.22.2 ](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/tree/0.22.2)is out for `django-elasticsearch-dsl-drf` which is tested against Django 3.2

**Comment by jmbowman** [comment]
@jramnai Great, thanks for following up on that!
