### ISSUE TITLE
Update or replace sorl-thumbnail

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#25]
We use the package [sorl-thumbnail](https://github.com/jazzband/sorl-thumbnail) in edx/django-wiki, edx/ecommerce, edx/edx-platform. It hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by jramnai** [comment]
@jmbowman, I am taking this one. Related [PR - #674](https://github.com/jazzband/sorl-thumbnail/pull/674)

**Comment by natabene** [comment]
@jramnai Thank you so much for looking into this, I appreciate. I will assign this to you. I see the related PR merged, please post here once the issue for version bump merges. Thanks!

**Comment by natabene** [comment]
@jramnai Looks like we are just waiting for a new release, right?

**Comment by jramnai** [comment]
Yes @natabene, waiting for the new release. I have pinged the project manager, waiting for his reply.
