### ISSUE TITLE
Update or replace django-hijack

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#27]
We use the package [django-hijack](https://github.com/django-hijack/django-hijack) in edx/credentials. It hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by jramnai** [comment]
@jmbowman, required [PR](https://github.com/django-hijack/django-hijack/pull/322) to support Django 3.2 has been merged on the master branch. Follow up [issue](https://github.com/django-hijack/django-hijack/issues/323) for version bump.

**Comment by Mogost** [comment]
`django-hijack` supports django version 3.2. 
The v3 of `django-hijack` has been completely rewritten with an emphasis on security. I recommend that you uninstall the current integration and install following the current [instructions](https://github.com/django-hijack/django-hijack/blob/master/docs/index.md). 

_Also, as far as I know, although django-hijack v2 does not declare to support django==3.2, it actually does._

**Comment by jmbowman** [comment]
Thanks for the updates, both of you!  I'll close this out as we now have a path forward to Django 3.2 support with a PyPI release, even if it will require a bit of refactoring.  (But @jramnai , please speak up if you have any interest in attempting that upgrade in the credentials repo.)
