### ISSUE TITLE
Update or replace django-fsm

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#28]
We use the package [django-fsm](https://github.com/kmmbvnr/django-fsm) in edx/course-discovery. It hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by jramnai** [comment]
@jmbowman, `django-fsm` is tested against Django 3.2 with the master branch, just a version bump is required. I have created an [issue](https://github.com/viewflow/django-fsm/issues/267) with it.

**Comment by jmbowman** [comment]
@jramnai Thanks for looking into this!  From the [maintainer's response](https://github.com/viewflow/django-fsm/issues/267#issuecomment-908208651) on your issue and a quick search of the course-discovery code, it looks like we should be ok for now with the latest PyPI release.  It looks like at least one major feature isn't working under 3.2 yet, but we don't use that feature yet and it's being worked on.  I'll go ahead and close this.
