### ISSUE TITLE
Update or replace djangorestframework-expander

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#30]
We use the package [djangorestframework-expander](https://github.com/silverlogic/djangorestframework-expander) in edx/blockstore. It hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by mariajgrimaldi** [comment]
Hi there!

I searched for `expander` -how djangorestframework-expander is imported for usage- and this was the result: https://github.com/edx/blockstore/search?q=expander

It seems like it's just a requirement but it's not being used

**Comment by natabene** [comment]
@mariajgrimaldi Thank you for looking into this, may I assign this issue to you?

**Comment by mariajgrimaldi** [comment]
Yes! Go ahead @natabene. Thanks

**Comment by UsamaSadiq** [comment]
Hi @mariajgrimaldi 
Thanks for your effort on this. Would you be able to create a PR in `openedx/blockstore` to remove the `djangorestframework-expander` from the requirements? Since it isn't being used, we should close this issue after removing it from the dependencies.

**Comment by mariajgrimaldi** [comment]
I'm on it! @UsamaSadiq

**Comment by mariajgrimaldi** [comment]
PR: https://github.com/openedx/blockstore/pull/150

**Comment by UsamaSadiq** [comment]
Thanks @mariajgrimaldi. I'll get the review on this PR and will update you soon.

**Comment by UsamaSadiq** [comment]
Hi @mariajgrimaldi thanks for your efforts. The PR has been reviewed and merged so I'll mark this issue as done.
