### ISSUE TITLE
Replace model-mommy dependency

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#31]
We use the package [model-mommy](https://github.com/vandersonmota/model_mommy) in edx/openedxstats. This package is no longer maintained and was replaced by 'model-bakery'. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by kasittig** [comment]
Hey @Jawayria - my PR was merged so I think this issue is complete!

**Comment by natabene** [comment]
@jmbowman Can you please check if we are done here? 
@kasittig Thank you for looking into this!

**Comment by natabene** [comment]
@awais786 Can you please check if this is complete, and if yes, confirm here, close the issue and update the dependency excel spreadsheet?

**Comment by Jawayria** [comment]
> @awais786 Can you please check if this is complete, and if yes, confirm here, close the issue and update the dependency excel spreadsheet?

Yes its completed
