### ISSUE TITLE
Update or replace django-parler

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#33]
We use the package [django-parler](https://github.com/edoburu/django-parler) in edx/course-discovery. It hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by ericfab179** [comment]
Hi @natabene , I would like to work on this issue, could you please assign it to me ? Thanks

**Comment by natabene** [comment]
@ericfab179 Thank you so much for looking into this, I appreciate. I am assigning to you.

**Comment by natabene** [comment]
@ericfab179 Just checking if you had a chance to look into this, please share any updates.

**Comment by ericfab179** [comment]
Hi @natabene, I created an issue trying to contact the django-parler maintainer because some PRs need to be merged in order to make django-parler compatible with Django 3.2 https://github.com/django-parler/django-parler/issues/303
I will let you know if I can make progress on this.

**Comment by natabene** [comment]
@ericfab179 Thanks for an update!

**Comment by natabene** [comment]
@ericfab179 Are we good now or is anything else needed?

**Comment by natabene** [comment]
@ericfab179 Thanks for an update, please let us review and we will update you here.

**Comment by UsamaSadiq** [comment]
Hi @ericfab179 
Thanks for your effort on this. I'll mark this as done and close the issue now.
