### ISSUE TITLE
Update or replace jsonfield2

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#34]
We use the package [jsonfield2](https://github.com/rpkilby/jsonfield2) in edx/ecommerce, edx/edx-bulk-grades, edx/edx-celeryutils, edx/edx-enterprise, edx/edx-ora2, edx/edx-platform, edx/edx-proctoring, edx/edx-submissions, edx/edx-zoom, edx/enterprise-catalog, edx/event-routing-backends, edx/license-manager, edx/staff_graded-xblock, edx/super-csv, edx/xblock-lti-consumer. It hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by MaferMazu** [comment]
I was working on issue #42  and I discovered that `jsonfield` supports django 3.2 and jsonfield2 was merged with jsonfield, perhaps the best option is to change the use of jsonfield2 to jsonfield but it would be necessary to test that in edx/edx-bulk-grades, edx/edx-celeryutils, edx/edx-enterprise, edx/edx-ora2, edx/edx-platform, edx/edx-proctoring, edx/edx-submissions, edx/edx-zoom, edx/enterprise-catalog, edx/event-routing-backends, edx/license-manager, edx/staff_graded-xblock, edx/super-csv and edx/xblock-lti-consumer. I could work on this.

**Comment by MaferMazu** [comment]
I don't know if adding django 3.2 in the tests is enough to say that jsonfield supports django3.2. If so, what would be the steps to follow to resolve this issue? Do a PR on each repository in the `django-32-upgrade` branch?

**Comment by natabene** [comment]
@MaferMazu Thank you so much for looking into this. @jmbowman Could you help us out here?

**Comment by jmbowman** [comment]
Ok, then since we have a path forward on getting all jsonfield2 and jsonfield package usage updated to work with Django 3.2, I'll go ahead and close this out.  The actual upgrades to the latest jsonfield package are in progress and can be handled as part of the IDA updating work.  Thanks for helping sort all this out!
