### ISSUE TITLE
Update or replace django-model-utils

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#35]
We use the package [django-model-utils](https://github.com/jazzband/django-model-utils) in edx/completion, edx/course-discovery, edx/django-user-tasks, edx/ecommerce, edx/edx-analytics-dashboard, edx/edx-analytics-data-api, edx/edx-bulk-grades, edx/edx-celeryutils, edx/edx-cookiecutters, edx/edx-enterprise, edx/edx-enterprise-data, edx/edx-milestones, edx/edx-notifications, edx/edx-ora2, edx/edx-organizations, edx/edx-platform, edx/edx-proctoring, edx/edx-rbac, edx/edx-submissions and some other repos. It hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by kasittig** [comment]
It looks like a PR to enable support for Django 3.2 was merged in early April but that there hasn't been a new release of django-model-utils since then. I opened an issue to ask the maintainers to release a new package to enable this upgrade.

**Comment by natabene** [comment]
@kasittig Thank you so much for picking this up, I appreciate. Please let me know once it is done by updating here.

**Comment by UsamaSadiq** [comment]
`django-model-utils` version [4.2.0](https://pypi.org/project/django-model-utils/4.2.0/) has been released with `Django 3.2` support so this issue can be closed now.

**Comment by UsamaSadiq** [comment]
@kasittig Thanks for your efforts on this issue. Please let me know if there is anything further to do on this issue.
