### ISSUE TITLE
[edx-opaque-keys]: Add Support for Django 4.2

### ISSUE THREAD

**Issue by UsamaSadiq** [edx/upgrades#388]
## Description
Follow and Complete all of the following steps for the issue to be marked as done.

- [x] Update tox & Github action workflow using modernisers to add support for Django 4.2
- [x] Remove any versions of Python earlier than 3.8 from tox.ini, .travis.yml, and GitHub Actions workflows.
- [x] Update the trove classifiers in setup.py, setup.cfg or pyproject.toml files.
- [x] Run and verify all tests are passing in the CI for Django 4.2
- [x] Run available code-mods to fix the failing tests
- [x] Add CHANGELOG entry with description “Support added for Django 4.2”
- [x] Bump the package version and release a new version on GitHub & PyPI (whichever is applicable)
- [x] Update the repo support field in the Dependency Upgrade Sheet.

**Comment by salman2013** [comment]
There is no Django package in this repo.

**Comment by zubairshakoorarbisoft** [comment]
It had the dependencies so made a PR and merged https://github.com/openedx/opaque-keys/pull/258 @salman2013
