### ISSUE TITLE
Unpin more edx-platform dependencies

### ISSUE THREAD

**Issue by jmbowman** [edx/upgrades#392]
There are now more than 30 edx-platform Python dependencies which are pinned to stale versions for various reasons.  After resolving any existing issues for unpinning some of them, list here the ones that still need to be unpinned and create new issues for them.  This is something we should tackle soon, as it's starting to cause other problems and is likely to block the Python 3.11 upgrade.

**Comment by UsamaSadiq** [comment]
Most of the dependencies have been updated when upgrading to Django 4.2 and Python 3.11 so now closing this issue out. Individual issues will be created to remove constraints explicitly to have better tracking of the work.
