### ISSUE TITLE
Replace django-ratelimit-backend

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#40]
We use the package [django-ratelimit-backend](https://github.com/brutasse/django-ratelimit-backend) in edx/edx-platform. This package isn't maintained anymore and edx will deprecate it. It doesn't have support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by mariajgrimaldi** [comment]
Hello! 

I found [this](https://github.com/brutasse/django-ratelimit-backend/issues/53) issue opened by @jmbowman in the django-ratelimit-backend repo. Is this issue still needed?

**Comment by natabene** [comment]
@mariajgrimaldi Thanks for pointing, we will handle this deprecation ourselves, so I will close this issue on this board.
