### ISSUE TITLE
Update or replace jsonfield

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#42]
We use the package [jsonfield](https://github.com/rpkilby/jsonfield) in edx/course-discovery. It hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by MaferMazu** [comment]
I saw that someone was trying to run tests for this package with Django 3.2 and the tests failed. I think I can correct it or find another alternative. I will be working on this.

**Comment by natabene** [comment]
@MaferMazu Thank you for reaching out, I highly appreciate your interest and help with this. I have assigned this task to you. Please feel free to open a PR once you are ready, I will take care of it from there on.

**Comment by MaferMazu** [comment]
The jsonfield library supports django 3.2, the only thing missing is that the author approves some PRs to add the corresponding tests. I already wrote to the author and the maintainer.

I took the tests that are in the PRs and jsonfield supports django 3.2
Test: https://app.circleci.com/pipelines/github/MaferMazu/jsonfield?branch=mfmz%2Ffix-ci-and-test-django3.2

**Comment by natabene** [comment]
@MaferMazu Thank you, I hope you hear back from them soon. Please keep us posted here.

**Comment by MaferMazu** [comment]
This issue would be resolved equal to #34  which is already closed.

**Comment by jmbowman** [comment]
Agreed, closing it as we have an upgrade path now.  Thanks for helping sort this out!  Tl;dr for those following up on this issue later: we believe the latest PyPI release of jsonfield should work with Django 3.2.
