### ISSUE TITLE
Update or replace django-elasticsearch-debug-toolbar

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#43]
We use the package [django-elasticsearch-debug-toolbar](https://github.com/Benoss/django-elasticsearch-debug-toolbar) in edx/course-discovery. It hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by ghassanmas** [comment]
Status: Waiting for maintainer 
Relevant RR is opened Benoss/django-elasticsearch-debug-toolbar/pull/14 and an issue as well /Benoss/django-elasticsearch-debug-toolbar/issues/16

**Comment by natabene** [comment]
@ghassanmas Thanks so much for an update!

**Comment by natabene** [comment]
@ghassanmas I will assign this to you if you don't mind.

**Comment by UsamaSadiq** [comment]
PR has been merged and the updated version is being used in course-discovery now. 
@ghassanmas Thanks for your efforts on this.
