### ISSUE TITLE
Update or replace django-elasticsearch-dsl

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#53]
We use the package [django-elasticsearch-dsl](https://github.com/sabricot/django-elasticsearch-dsl) in edx/course-discovery, edx/edx-notes-api. It hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by jramnai** [comment]
@natabene, I have opened a [PR - #371](https://github.com/django-es/django-elasticsearch-dsl/pull/371) for Django 3.1 and 3.2 support.

**Comment by natabene** [comment]
@jramnai Thanks so much for an update!

**Comment by natabene** [comment]
@jramnai I am excited to see this being so close to complete. Hopefully this will land before this weekend.

**Comment by jramnai** [comment]
Yes @natabene. Rebased and waiting for the workflow to run.

**Comment by natabene** [comment]
@jramnai Excellent, thanks so much.

**Comment by natabene** [comment]
@jramnai Just checking, if there have been any news.
