### ISSUE TITLE
Update or replace pytest-django-ordering

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#55]
We use the package [pytest-django-ordering](https://github.com/rlucioni/pytest-django-ordering) in edx/course-discovery, edx/ecommerce. It hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by cmltaWt0** [comment]
HI @natabene.

I'm happy to take this one.

**Comment by cmltaWt0** [comment]
Have to mention that https://github.com/edx/upgrades/issues/20 is a showstopper for course-discovery Django 3.0+ compatibility and must be upgraded to simplify any further work with course-discovery repo.

**Comment by natabene** [comment]
@cmltaWt0 Thank you so much for reaching out, I appreciate. @jmbowman Please see previous comment from @cmltaWt0.

**Comment by cmltaWt0** [comment]
Maintainer doesn't have any plans for Django 3.2 support.
I'll analyze an effort to create a PR to do it by myself and then will decide are we going to help the maintainer or find an alternative (as an alternative we can use pytest-ordering directly)

**Comment by natabene** [comment]
@cmltaWt0 Thank you very much for an update!

**Comment by cmltaWt0** [comment]
Further investigation of the history of pytest-django-ordering reveals the interesting conclusion - we don't need this plugin since repos use [pytest-django>=3.9](https://pytest-django.readthedocs.io/en/latest/changelog.html?highlight=ordering#v3-9-0-2020-03-31) where an appropriate [bugfix](https://pytest-django.readthedocs.io/en/latest/changelog.html?highlight=ordering#id10) was introduced.

There is a code from [pytest-django-ordering](https://github.com/rlucioni/pytest-django-ordering/blob/master/pytest_django_ordering/plugin.py#L12):
```python
@pytest.hookimpl(trylast=True)
def pytest_collection_modifyitems(items):
    def get_marker_transaction(test):
        try:
            marker = test.get_closest_marker('django_db')
        except AttributeError:
            # pytest < 3.6.0
            marker = test.get_marker('django_db')

        if marker:
            validate_django_db(marker)
            try:
                return marker.kwargs.get('transaction')
            except AttributeError:
                # pytest-django < 3.3.0
                return marker.transaction

        return None

    def has_fixture(test, fixture):
        fixturenames = getattr(test, 'fixturenames', None)
        return fixturenames and fixture in fixturenames

    def weight_test_case(test):
        """
        Key function for ordering test cases like the Django test runner.
        """
        is_test_case_subclass = test.cls and issubclass(test.cls, TestCase)
        is_transaction_test_case_subclass = test.cls and issubclass(test.cls, TransactionTestCase)

        if is_test_case_subclass or get_marker_transaction(test) is False:
            return 0
        elif has_fixture(test, 'db'):
            return 0

        if is_transaction_test_case_subclass or get_marker_transaction(test) is True:
            return 1
        elif has_fixture(test, 'transactional_db'):
            return 1

        return 0

    items.sort(key=weight_test_case)
```

which is almost completely replaced in [pytest-django>=3.9](https://github.com/pytest-dev/pytest-django/blob/master/pytest_django/plugin.py#L366) plugin:

```python
@pytest.hookimpl(tryfirst=True)
def pytest_collection_modifyitems(items: List[pytest.Item]) -> None:
    # If Django is not configured we don't need to bother
    if not django_settings_is_configured():
        return

    from django.test import TestCase, TransactionTestCase

    def get_order_number(test: pytest.Item) -> int:
        test_cls = getattr(test, "cls", None)
        if test_cls:
            # Beware, TestCase is a subclass of TransactionTestCase
            if issubclass(test_cls, TestCase):
                return 0
            if issubclass(test_cls, TransactionTestCase):
                return 1

        marker_db = test.get_closest_marker('django_db')
        if not marker_db:
            transaction = None
        else:
            transaction = validate_django_db(marker_db)[0]
            if transaction is True:
                return 1

        fixtures = getattr(test, 'fixturenames', [])
        if "transactional_db" in fixtures:
            return 1

        if transaction is False:
            return 0
        if "db" in fixtures:
            return 0

        return 2

    items.sort(key=get_order_number)
```


So I'm going to remove this dependency completely, test it and open PRs into discovery and ecommerce repos.


Related links:
- https://github.com/pytest-dev/pytest-django/issues/827
- https://github.com/pytest-dev/pytest-django/pull/830
- https://github.com/pytest-dev/pytest-django/pull/820

**Comment by natabene** [comment]
@cmltaWt0 Thank you for an update, I appreciate.

**Comment by mraarif** [comment]
@natabene the change introduced by @cmltaWt0 to remove `pytest-django-ordering` seems reasonable

**Comment by cmltaWt0** [comment]
@natabene Let's close it.
