### ISSUE TITLE
Update or replace authlib

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#56]
We use the package [authlib](https://github.com/lepture/authlib) in edx/course-discovery, edx/tubular. This is a python library but running tests against Django and flask. It seems like it hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by mariajgrimaldi** [comment]
Hi there!

I couldn't find any explicit affirmation about supporting Django 3.2, but then I ran with the tests executions and found that they are actually using Django 3.2:
![image](https://user-images.githubusercontent.com/64440265/133493809-ce6742c4-2c5c-4790-814f-9d094e60464a.png)
https://github.com/lepture/authlib/runs/3542288706

So maybe it's safe to say that it already supports Django 3.2

What do you say?

**Comment by natabene** [comment]
@mariajgrimaldi Thank you so much for looking into this! @awais786 What do you think?

**Comment by awais786** [comment]
Yes it is running tests with `django32`, We can safely consider this package as done

**Comment by awais786** [comment]
@mariajgrimaldi I am searching the `authlib` supporting version with django2.2+ version.
course-discovery is using this authlib==0.15.4.
You can see https://github.com/lepture/authlib/tree/v0.15.4 build history and see lot of failures. I am assuming `authlib==0.15.4` is not supporting >django2.2 versions and we need to wait for the latest release.

What do you think ?

**Comment by mariajgrimaldi** [comment]
You're right, @awais786. I opened a new issue asking for a version bump. I'll keep you posted

**Comment by natabene** [comment]
Reopening it waiting for a new release.

**Comment by mariajgrimaldi** [comment]
They have a beta release: https://github.com/lepture/authlib/issues/384#issuecomment-922450778

**Comment by natabene** [comment]
@jmbowman Do you want to wait or are you happy with beta?

**Comment by lepture** [comment]
@natabene I'm using the beta version for my own product (https://typlog.com/) right now. I just rewrote the project from Flask to Django, and it is using the latest Django version.
