### ISSUE TITLE
Update or replace dry-rest-permissions

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#58]
We use the package [dry-rest-permissions](https://github.com/Helioscene/dry-rest-permissions) in edx/course-discovery. Last commit to this package's repository was made in 2018 and it hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by BbrSofiane** [comment]
Hi, I can take on this issue

**Comment by natabene** [comment]
@BbrSofiane Thanks so much for reaching out, I appreciate! Please let me know once this is done.

**Comment by natabene** [comment]
@BbrSofiane Just checking if there have been any updates on this, please let me know when you have a chance.

**Comment by BbrSofiane** [comment]
@natabene Apologies for the late reply. I don't think I will have to look at this one anymore.

**Comment by natabene** [comment]
@BbrSofiane Thank you for an update! Moving this back to to do.

**Comment by giovannicimolin** [comment]
@natabene I can look at it in the next sprint (starting Dec 14).

**Comment by giovannicimolin** [comment]
@natabene I think you assigned it to the wrong person? 

I offered to work on this because it was on the backlog, but if there's already an assignee I can drop this.

**Comment by natabene** [comment]
@giovannicimolin Indeed, thanks for catching this. Reassigning to you.

**Comment by UsamaSadiq** [comment]
Hi @giovannicimolin Is there any progress on this issue or any plan in working for this issue? Please let us know if you need any help in finishing this up. 
Thanks.

**Comment by giovannicimolin** [comment]
@UsamaSadiq @natabene Dua to a mistake in planning, I ended up not planing time for this for the current sprint (Jan 12-25), so I won't be able to replace the library on short notice. Feel free to reassign this work if it's urgent.
 
The original library was abandoned, then someone forked it and started maintaining it (https://github.com/FJNR-inc/dry-rest-permissions - even changed the link from Django docs), but it seems like the new fork is also unmaintained and doesn't support Django 3.2.

**Comment by giovannicimolin** [comment]
@natabene Picking this up again.

**Comment by giovannicimolin** [comment]
@natabene Just a gently nudge: this is ready for review.
https://github.com/openedx/course-discovery/pull/3297

**Comment by giovannicimolin** [comment]
@natabene PR merged :)

**Comment by UsamaSadiq** [comment]
@giovannicimolin Thanks for your efforts on this issue. I'll close this issue now.
