### ISSUE TITLE
Update or replace django-sortedm2m

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#59]
We use the package [django-sortedm2m](https://github.com/jazzband/django-sortedm2m) in edx/course-discovery, edx/credentials. It hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by magajh** [comment]
@natabene  A PR that adds support for Django 3.2 was already merged into master, but there hasn't been a new release since then. I have created an issue to make a new release of the package to enable this upgrade https://github.com/jazzband/django-sortedm2m/issues/188

**Comment by natabene** [comment]
@magajh Thank you for picking this up and looking into this, I appreciate! Please update here on your progress.

**Comment by magajh** [comment]
@natabene Django 3.2 is supported now with the release [3.1.0](https://github.com/jazzband/django-sortedm2m/releases/tag/3.1.0). However, this new version has not been published to PyPi.  I already left another comment to see if they are going to publish it any time soon

**Comment by natabene** [comment]
@magajh Great, thanks so much for an update. @Jawayria At which point do we mark it in the Dependencies table as done?

**Comment by awais786** [comment]
@natabene yes 3.2 support is added but still there is no PR so we can add a comment in sheet, but no need to change the status.

**Comment by awais786** [comment]
we can close this new release is available.

**Comment by natabene** [comment]
This is done now.
