### ISSUE TITLE
Update or replace django-modelcluster

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#6]
We use the package in [django-modelcluster](https://github.com/wagtail/django-modelcluster) in edx/portal-designer. It hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by MaferMazu** [comment]
I can take a look at this

**Comment by natabene** [comment]
@MaferMazu Thank you very much for picking this up! I am assigning this to you, please update here on your progress.

**Comment by natabene** [comment]
@MaferMazu Just checking if you had a chance to look into this.

**Comment by MaferMazu** [comment]
I tried to add test to django-modelcluster with django32 environment and they did not pass, so i create an [issue](https://github.com/wagtail/django-modelcluster/issues/142) asking if they plan to do a new release that supports django 32. I hope they answer me.

**Comment by natabene** [comment]
@MaferMazu Thanks for an update!

**Comment by UsamaSadiq** [comment]
`Django 3.2` support added and tests fixed in the new release [django-modelcluster==5.2](https://github.com/wagtail/django-modelcluster/releases/tag/v5.2) so marking this issue as done. 
@MaferMazu Thank you for your efforts on this issue.
