### ISSUE TITLE
Update or replace drf-nested-routers

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#60]
We use the package [drf-nested-routers](https://github.com/alanjds/drf-nested-routers) in edx/blockstore, edx/license-manager. It hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by jramnai** [comment]
@natabene, I will take this and it is already tested against Django 3.2 on the master branch but the latest PyPI version isn't.

I have created a [PR](https://github.com/alanjds/drf-nested-routers/pull/243) to add Django 3.2 classifier and will raise an issue once it is merged.

**Comment by natabene** [comment]
@jramnai Thanks so much for looking into this, I appreciate. Please post updates about your progress here.

**Comment by natabene** [comment]
@jramnai Just checking what is left here, please update us.

**Comment by jramnai** [comment]
@natabene, the PR is merged and I have also created [an issue](https://github.com/alanjds/drf-nested-routers/issues/244) for version bump.

>Sure. The last change on master is dated from 7d ago. I use to wait at least a couple weeks before releasing versions, allowing people that target master to report newly introduced issues.
In meantime, could you do the development targeting the github master branch?

^ Maintainer's comment.

**Comment by jramnai** [comment]
@natabene, as the new version is released on PyPI I guess we can close this.

@alanjds thanks for the version bump.
