### ISSUE TITLE
Update or replace django-pdb

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#61]
We use the package [django-pdb](https://github.com/tomchristie/django-pdb) in edx/ubcpi. Last commit to this package's repository was made in 2018 and it hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by Squirrel18** [comment]
Hi, @natabene I would like to contribute to this problem, could you please assign it to me?

**Comment by natabene** [comment]
@Squirrel18 Sure, thank you for picking this up, I will assign to you.

**Comment by UsamaSadiq** [comment]
@natabene since the `edx/ubcpi` has now been archived and we are using its upstream repo so I'll mark this issue as `Done` and close this.
