### ISSUE TITLE
Update or replace django-soapbox

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#63]
We use the package [django-soapbox](https://github.com/ubernostrum/django-soapbox) in edx/edx-analytics-dashboard. It hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by NeOneSoft** [comment]
Hello @natabene, could you assign me to this issue please! Thank you so much

**Comment by natabene** [comment]
@NeOneSoft Sure, thank you so much for picking this up! Please post updated about your progress here.

**Comment by NeOneSoft** [comment]
Hi @natabene, I' already created a PR for the package however the last commit on this repo was on Dec 12, 2020 . I sent an email to the mantainer in order to ask for help to review it.

**Comment by NeOneSoft** [comment]
Hi @natabene I suggest to keep using django-soapbox since tests were ran successfully for Django 3.2 even tough this is not mentioned in the repo and I could not contact with the maintainer yet.

**Comment by natabene** [comment]
@Jawayria Please let me know what you think.

**Comment by awais786** [comment]
@NeOneSoft It make sense to me and [edx-analytics](https://github.com/edx/edx-analytics-dashboard/blob/master/requirements/base.txt#L39) already deployed with django32 and this package is working fine.
We can close this ticket @natabene

**Comment by NeOneSoft** [comment]
Thank you @natabene , @awais786 , @Jawayria  for your support = )!!
