### ISSUE TITLE
Update or replace django-sphinx-autodoc

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#66]
We use the package [django-sphinx-autodoc](https://github.com/Fandekasp/django-sphinx-autodoc) in edx/ease.This package was last released in 2011 and it hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by NeOneSoft** [comment]
Hi @Jawayria I think that this repo [https://github.com/Fandekasp/django-sphinx-autodoc] doesn't exists anymore

**Comment by natabene** [comment]
@NeOneSoft Thank you so much for looking into this. @Jawayria Please review response form @NeOneSoft

**Comment by natabene** [comment]
@NeOneSoft We are still looking into this, please stay tuned.

**Comment by NeOneSoft** [comment]
For sure @natabene!!

**Comment by awais786** [comment]
@NeOneSoft it was added in this https://github.com/edx/ease/pull/86/files I don't think it has any output. You can remove this from the repo `edx/ease`. After removing we can close this ticket.

**Comment by NeOneSoft** [comment]
Thank you for your response @awais786 I created a PR in order to close this ticket!!

**Comment by awais786** [comment]
@NeOneSoft Thanks for your contribution. I have merged your pr.

@natabene you can close this ticket.

**Comment by NeOneSoft** [comment]
Thank  you so much @awais786  @natabene !!!
