### ISSUE TITLE
Update or replace django-widget-tweaks

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#67]
We use the package [django-widget-tweaks](https://github.com/jazzband/django-widget-tweaks) in edx/ecommerce. It hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by jramnai** [comment]
@jmbowman, I am attempting this one. And here is my [PR](https://github.com/jazzband/django-widget-tweaks/pull/112) which tests the package against Django 3.2.

**Comment by natabene** [comment]
@jramnai Thank you for looking into this, I will assign this to you. Please update us on your progress here.

**Comment by jramnai** [comment]
@natabene, here is the [issue](https://github.com/jazzband/django-widget-tweaks/issues/114) for version bump as my PR has been merged.

**Comment by natabene** [comment]
@jramnai great, looking forward to the version bump.
