### ISSUE TITLE
Update or replace django-nose

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#68]
We use the package [django-nose](https://github.com/jazzband/django-nose) in edx/ubcpi, edx/xblock-in-video-quiz. It hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by ghassanmas** [comment]
I have just asked the orignal author for the repo, about how to move forward in order to upgarde it. 
Also for context worth [qouting](https://github.com/jazzband/django-nose#note-to-users) from the repo Readme.md 

> nose has been in maintenance mode since at least 2015. django-nose is in maintenance mode as well, and the sole maintainer is no longer an active user. See Jazzband.co to learn how django-nose is maintained and how you can help. New projects should consider using pytest, or unittest with the Django testing framework.

**Comment by jmbowman** [comment]
Yeah, I'm surprised there's still any usage of this; I thought we had it all replaced with pytest already.  I'm still figuring out if we can deprecate our ubcpi fork, do you have any interest in porting xblock-in-video-quiz over to use pytest instead?  There are a few [Jira tickets explaining how to do this for other repos](https://openedx.atlassian.net/issues/?jql=project%20%3D%20BOM%20AND%20text%20~%20%22nose%20pytest%22).

**Comment by ghassanmas** [comment]
@jmbowman I am currently in the process of migrating to `pytest`. The eample you sent seems helpful and relevant!. 
Just one note, to be clear there doesn't seems to be tests in the repo [xblock-in-video-quiz](https://github.com/edx/xblock-in-video-quiz/tree/master/invideoquiz)   right?, or am I missing somehting...

**Comment by awais786** [comment]
@natabene you can close this. Its completed.

**Comment by ghassanmas** [comment]
edx/ubcpi still uses django-nose as it appears here: https://github.com/edx/ubcpi/blob/29f066d2397383297312cb49eb62718fe0514d99/requirements/test.txt#L6 .

**Comment by natabene** [comment]
@awais786 What do you think regarding the last comment?

**Comment by awais786** [comment]
I only checked `xblock-in-video-quiz` and it was done, but edx/ubcpi need updation. 
@ghassanmas needs similar PR in edx/ubcpi also.

https://github.com/edx/ubcpi/blob/29f066d2397383297312cb49eb62718fe0514d99/settings/test.py#L34

**Comment by UsamaSadiq** [comment]
@ghassanmas both https://github.com/edx/upgrades/issues/35 and https://github.com/edx/upgrades/issues/14 have been closed now with `Django 3.2` support. Please let me know if we can now continue working on `edx/ubcpi` upgrade since the blockers have been resolved now.
Thanks.

**Comment by UsamaSadiq** [comment]
[edx/ubcpi](https://github.com/edx-unsupported/ubcpi) has now been archived since the upstream repo is being used now in edX. 
@ghassanmas thanks for your efforts on this. I'll close this issue now since it has been completed.
