### ISSUE TITLE
Update or replace edx-jsme

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#69]
We use the package [edx-jsme](https://github.com/jazkarta/edx-jsme) in edx/edx-platform. Last commit to this package's repo was made in 2017 and it hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by mariajgrimaldi** [comment]
I'm not sure how to proceed here. 

The package uses Django in [this line](https://github.com/jazkarta/edx-jsme/blob/master/edx_jsme/__init__.py#L9) and that is used just [here](https://github.com/jazkarta/edx-jsme/blob/690dbf75441fa91c7c4899df0b83d77f7deb5458/edx_jsme/__init__.py#L42). 

`from Django.utils.translation import ugettext as _` can still be used in Django 3.2, proof [here](https://github.com/django/django/blob/45a0c54b670a5d9766fd466c0e05bcc544e47890/django/utils/translation/__init__.py#L97), so we are safe there.

I also tried to run the package tests, but they depend on the Capa module.

Is what I mentioned enough to say that it supports Django 3.2 and it does not need any intervention?

**Comment by natabene** [comment]
@Jawayria Could you please help @mariajgrimaldi here?

**Comment by mariajgrimaldi** [comment]
of course @natabene! Thanks :)

**Comment by Jawayria** [comment]
Yes @mariajgrimaldi we don't need any intervention in this package. Thanks for having a look at it. @natabene we can close this issue.

**Comment by natabene** [comment]
I will follow up with natea about doing a release and whether they still maintain this or it needs another owner.

**Comment by mariajgrimaldi** [comment]
@natabene, thanks for the update. Would you mind letting me know if you need any help?

**Comment by natabene** [comment]
@mariajgrimaldi Thanks for offering, I am good.

**Comment by natabene** [comment]
Decided to deprecate, effort tracked in https://openedx.atlassian.net/browse/DEPR-173. Closing this ticket.
