### ISSUE TITLE
Update or replace django-mptt

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#7]
We use the package in [django-mptt](https://github.com/django-mptt/django-mptt) in edx/django-wiki and edx/edx-platform. It hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by elvinquero** [comment]
Hi there! I was looking forward to work in this. I realized django-mptt is unmaintained and they recommend using the django-treebeard library that has already support for Django 3.2. I will give it a look.

**Comment by natabene** [comment]
@elvinquero Thank you for reaching out, I highly appreciate your interest and help with this. I have assigned this task to you. Please feel free to open a PR once you are ready, I will take care of it from there on.

**Comment by jmbowman** [comment]
Some context that might be useful - Open edX forked and maintains a rather old version of django-wiki - https://github.com/edx/django-wiki .  It's diverged enough from upstream that essentially we'll never be going back to an official django-wiki release, but at the same time is a minor enough feature of the platform that we're not looking to invest more in it right now than keeping it working and secure.

Also, it looks like django-mptt did get an [update](https://github.com/django-mptt/django-mptt/pull/786) to test against Django 3.2, it just hasn't been released yet.  So this may be as simple as asking the repo owner if they intend to make a release including that, and install directly from GitHub if not.

**Comment by elvinquero** [comment]
I finally got in touch with the maintainers of the django-mptt library and we agreed that support for Django 3.2 could be added. I will keep you updated.

**Comment by natabene** [comment]
@elvinquero Thank you so much for an update.

**Comment by jmbowman** [comment]
I see that django-mptt 0.13.0 was just released with Python 3.9 and Django 3.2 support; thanks for helping out with this!

**Comment by natabene** [comment]
@jmbowman If this is resolved, should this issue be closed?

**Comment by jmbowman** [comment]
django-wiki still needs to be updated to run its tests with the new version, but a routine dependencies upgrade in edx-platform already pulled in and deployed the new django-mptt version.  So yes, this can be closed and we'll just follow up with a round of dependency updates for the django-wiki tests.
