### ISSUE TITLE
Update or replace edx-sga

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#71]
We use the package [edx-sga](https://github.com/mitodl/edx-sga) in edx/edx-platform. It hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by pdpinch** [comment]
MIT Open Learning will update this xBlock. Issue at https://github.com/mitodl/edx-sga/issues/303

**Comment by natabene** [comment]
@pdpinch Thank you, I am assigning this to you.

**Comment by pdpinch** [comment]
@umarmughal824 wrote [a PR for this fix](https://github.com/mitodl/edx-sga/pull/304), but we can't test it until there is a django 3.2 compatible version of edx-platform.

**Comment by natabene** [comment]
@pdpinch Thank you for an update. @Jawayria FYI this is waiting on edx-platform.

**Comment by awais786** [comment]
Comment added on PR. No need to drop django22 support.
