### ISSUE TITLE
Replace rate-xblock dependency

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#72]
We use the package [rate-xblock](https://github.com/pmitros/RateXBlock) in edx/edx-platform. This package is obsolete and deprecated. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by mariajgrimaldi** [comment]
The [master branch](https://github.com/pmitros/FeedbackXBlock) now supports Django 3.2. I asked for a new release. Let's wait and see

**Comment by jmbowman** [comment]
Afraid there was some confusion here, we're actually using a fork of this in the openedx GitHub org: https://github.com/openedx/RateXBlock .  The PR above should definitely help, I'm hoping it's a simple matter of applying those changes to our fork. https://openedx.atlassian.net/browse/BOM-3200 should cover that, so I'll go ahead and close this issue.
