### ISSUE TITLE
Update or replace xblock-poll

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#73]
We use the package [xblock-poll](https://github.com/open-craft/xblock-poll) in edx/edx-platform. It hasn't yet added support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by natabene** [comment]
@arbrandes This issue.

**Comment by natabene** [comment]
@arbrandes Not sure why I pinged you here, were you planning on picking this up?

**Comment by arbrandes** [comment]
@natabene, I was - still am!  Just a bit late on it, though.

**Comment by natabene** [comment]
@arbrandes Got it, thanks for an update!

**Comment by arbrandes** [comment]
@natabene, apologies!  I haven't managed to tackle this, yet.  But it is high in my list.  I intend to have it done before the week's out.

**Comment by gabor-boros** [comment]
Hello @natabene,
The related PR is merged and the Xblock will be bumped as part of https://github.com/edx/edx-platform/pull/29046.
