### ISSUE TITLE
Update or replace django-solo

### ISSUE THREAD

**Issue by Jawayria** [edx/upgrades#78]
We use the package [django-solo](https://github.com/lazybird/django-solo) in edx/course-discovery, edx/ecommerce, edx/taxonomy-connector. It doesn't have support for Django3.2. Please follow the guidance in https://openedx.atlassian.net/wiki/spaces/AC/pages/3036972032/Handling+Outdated+Dependencies to resolve the problem this poses for the Open edX Django 3.2 upgrade.

**Comment by ghassanmas** [comment]
So the pacakge have been updated recently, a [PR](https://github.com/lazybird/django-solo/pull/91) have been merged related to supporting the new Django implementation, the author haven't replied to my issue thought,  however so it depends is the PR above suffient for resolving this?

**Comment by awais786** [comment]
@ghassanmas please run these [codemods](https://github.com/edx/repo-tools/tree/master/edx_repo_tools/codemods/django3) on this Repo to see if there any any changes.

**Comment by ghassanmas** [comment]
@awais786 Is there an example of how to do that, it would save me a lot of time if there is at least some guideline. I couldn't get how to do that by just following the doc/readme on [edx/repo-tools](https://github.com/edx/repo-tools). I speculate that I would have to add a test file replication or something?

**Comment by Jawayria** [comment]
@ghassanmas you can use the following set of commands to run codemods
```
pip install edx-repo-tools
modernize_tox --path={path to tox.ini}
modernize_travis --path={path to .travis.yml}                                                             #if the CI is on Travis
modernize_github_actions_django --path={path to CI GitHub workflow}                 #if CI uses GitHub Actions
remove_python2_unicode_compatible --path={path to package directory}
replace_unicode_with_str --path={path to package's directory}
replace_static --path={path to package's directory}
replace_render_to_response {path to package's directory}
add_django32_settings --setting_path={path to settings file}

```

**Comment by Jawayria** [comment]
@ghassanmas you can make a PR with the changes suggested by `replace_unicode_with_str` and `add_django32_settings` codemods.

**Comment by ghassanmas** [comment]
@Jawayria here is the PR lazybird/django-solo/pull/98, let me know if other changes are required

**Comment by Jawayria** [comment]
> @Jawayria here is the PR [lazybird/django-solo/pull/98](https://github.com/lazybird/django-solo/pull/98), let me know if other changes are required

@ghassanmas I guess we don't need any further changes but still can you please run tests with Django 3.2 once to verify that we are done?

**Comment by ghassanmas** [comment]
There was just a warning because the setting for the test wasn't updated, I have made a PR to fix it: https://github.com/lazybird/django-solo/pull/99 
Besides that, all good, tests passed without any errors or warnings.

**Comment by ghassanmas** [comment]
Since https://github.com/lazybird/django-solo/pull/99 is merged, I think this is ready to be labelled as done.

**Comment by natabene** [comment]
@ghassanmas Thanks for the update, let us look into this.

**Comment by natabene** [comment]
@ghassanmas It would be best if we wait for a release. Is this something you can pursue?

**Comment by ghassanmas** [comment]
Yes @netabene, I am on it. I will update you as soon as it's released

**Comment by ghassanmas** [comment]
@natabene https://github.com/lazybird/django-solo/releases/tag/1.2.0

**Comment by natabene** [comment]
Thanks, @ghassanmas !
