### ISSUE TITLE
Migrate eslint-config-edx

### ISSUE THREAD

**Issue by jmbowman** [edx/upgrades#79]
eslint-config-edx has been deprecated but it is still being used by many of our legacy frontends, including edx-platform, unfortunately.  So we need to migrate this package by removing its usages.

@aht007 has already started this work in https://2u-internal.atlassian.net/browse/BOM-3047 (which is private unless you have a 2U Jira account, there's an outdated public copy at https://openedx.atlassian.net/browse/BOM-3047).  Please check with him to see what's left to do on this.  As far as I know, the repos which still need to be migrated are:

- https://github.com/openedx/studio-frontend
- https://github.com/openedx/edx-analytics-dashboard
- https://github.com/openedx/edx-proctoring
- https://github.com/openedx/edx-ui-toolkit

Recent PRs done for this which could serve as examples can be found at:

- https://github.com/openedx/frontend-app-learner-portal-programs/pull/242
- https://github.com/openedx/frontend-component-cookie-policy-banner/pull/398
- https://github.com/openedx/stylelint-config-edx/pull/17

**Comment by BilalQamar95** [comment]
- [ ] Migrate eslint-config-edx for edx-proctoring
- [ ] Migrate eslint-config-edx  for edx-analytics-dashboard
