### ISSUE TITLE
Assist Arbi-BOM squad with Node 16 upgrade

### ISSUE THREAD

**Issue by jmbowman** [edx/upgrades#80]
The Arbi-BOM squad is most of the way through helping implement a major upgrade of the Open edX platform from Node 12 to Node 16, but there is still a long tail of tasks needed to finish this up (resolving a few CI problems, dropping Node 12 support in assorted repositories, finish migrating to `@edx/browserslist-config`, etc.)  Reach out to @Jawayria or @awais786 to determine the best way to assist with this; my tentative thoughts on priority are:

1. Figure out the best way to determine what tasks still need to be done.  There are a few open and in-progress Arbi-BOM Jira tickets, there's the spreadsheet at https://docs.google.com/spreadsheets/d/1fduFbAxIbckiwHKNCtc41ImAL_CFIl9hZcC4AjDkuvI/edit?usp=sharing which may not be completely up to date, etc.  Make sure somebody has a clear idea of what's left to be done, and write it down somewhere public (either that spreadsheet, or a page in the openedx wiki, or issues in this repo and board, etc.)
2. Assist on any tasks blocking Node 16 support in the upcoming Nutmeg release of Open edX which the Arbi-BOM squad either hasn't started yet or is stuck on (I'm not sure if any such tasks remain).
3. Take over other tasks in this project which Arbi-BOM hadn't gotten around to starting yet.

**Comment by Jawayria** [comment]
@jmbowman I've updated the status of the PRs on [Node 16 Upgrade & Shared Browserslist Config](https://docs.google.com/spreadsheets/d/1fduFbAxIbckiwHKNCtc41ImAL_CFIl9hZcC4AjDkuvI/edit#gid=0) spreadsheet that you mentioned in the description and also updated the [Node 16 upgrade status doc](https://docs.google.com/spreadsheets/d/1zY7UJAPBHbPBwOhuWJKM5oBSBSQJ1bXzc1HB8cztqbA/edit#gid=1094844783) that we're using to track the status of Node 16 upgrade.

**Comment by jmbowman** [comment]
Summarizing status from a discussion this morning: we believe all necessary PRs for this have been created, and we're just waiting for them all to be merged and deployed.  I'll go ahead and close this, and we can create new issues if we find any tasks that still need to be done.

**Comment by hurtstotouchfire** [comment]
FYI @jmbowman we've determined that the work required to upgrade Credentials to Node 16 is still a non-trivial amount. We're tracking that work here: https://github.com/openedx/credentials/issues/1791
