### ISSUE TITLE
Arbi-Bom: Upgrade libraries and packages in edx-platform.

### ISSUE THREAD

**Issue by awais786** [edx/upgrades#88]
Production is using these following packages related with mongodb. Most important is `pymongo`.

- pymongo==3.13.0
- MongoEngine==0.26.0 
- mongodbproxy

**AC:**

- ENSURE All above packages are upgraded to support mongodb 4.4.
- ENSURE we resolve any failing tests

**Comment by awais786** [comment]
`edx-platform` is using `pymongo==3.13.0`. As per their [documentation](https://pymongo.readthedocs.io/en/stable/changelog.html#changes-in-version-3-11-3) `Version 3.11 adds support for MongoDB 4.4`. So this part seems fine. 

`MongoEngine==0.26.0` and it also supported [mongodb4.4](https://github.com/MongoEngine/mongoengine/blob/94c373523274655360665292dd0e35ea9b5b935d/README.rst#supported-mongodb-versions)

`mongodbproxy` it is our personal fork and seems fine. but its old hash is in use in `edx-platform`

**Comment by awais786** [comment]
Looks fine but good to get a review from owning team.

**Comment by jmbowman** [comment]
If this is now blocked on owning team review, it should go on the maintenance board.  And is Arch-BOM the owner in this case as the owner for edx-platform parts not explicitly assigned elsewhere?

**Comment by jmbowman** [comment]
Is there still an open PR for this somewhere, or is this a stale issue?

**Comment by iamsobanjaved** [comment]
The latest release of mongodbproxy is now installed from PyPI, so closing this issue.
