### ISSUE TITLE
Arbi-Bom: Upgrade the devstack to support  4.4 in edx-platform

### ISSUE THREAD

**Issue by awais786** [edx/upgrades#90]
**Description**
As a devstack user I can test my service on Mongo 4.4 so that I can be ready for upgrading other environments.

**AC:**

- Modify [this script](https://github.com/edx/devstack/blob/master/upgrade_mongo_4_0.sh#L73-L100) to update to 4.4 in devstack and ask SRE to review and test.
- Ensure we can test import and export a course using devstack.
- ENSURE we post a message in dev, email to eng-all (template [here](https://openedx.atlassian.net/wiki/spaces/AC/pages/2992799913/Mongo+Email+Templates)) and if needed a post to https://discuss.openedx.org/.

**Implementation Details:**

- SRE have context on this work.
- Same ticket needs in cs-forums.

**Comment by iamsobanjaved** [comment]
SRE is finding a solution for backup for Mongo 4.4, so this will be blocked until a new solution is found.
