### ISSUE TITLE
Arbi-Bom: Point cs_comments_service in devstack at the new mongo 4.4 image

### ISSUE THREAD

**Issue by awais786** [edx/upgrades#91]
**Description**
As a devstack user I can test my service on Mongo 4.4 so that I can be ready for upgrading other environments.

**AC:**

- ENSURE we test that that we can add, edit and delete a comment ( separate ticket )

**Implementation Details:**

- SRE have context on this.
- SRE recommends doing this testing after completing this [ticket](https://github.com/edx/upgrades/issues/90)

**Comment by iamsobanjaved** [comment]
Done in https://github.com/openedx/devstack/pull/1011
